### ISSUE TITLE
Missing "prefix" parameter in Service creation of getDirectServiceProxyFromUrlString function

### ISSUE THREAD

**Issue by calairoh** [mia-platform/custom-plugin-lib#203]
When a URL is passed to the `getDirectServiceProxyFromUrlString` function, the created Service object does not contain the path of the passed URL as prefix.

The code snippet below shows the way in which the Service object is built:
```js
return serviceBuilder(
    completeUrl.hostname,
    requestMiaHeaders,
    {
      protocol: completeUrl.protocol,
      port: completeUrl.port,
      ...baseOptions,
    })
```

Example: if the URL is `http://example.com/path`, `/path` is not considered when building the Service object.

**Comment by davidebianchi** [comment]
This is now possible with the new http client and it will be released soon. I close the issue, since the other proxies are now deprecated.
