### ISSUE TITLE
Default parsing of response payload to JSON with statusCode 200 throw error if the payload is empty

### ISSUE THREAD

**Issue by MIA-Deltat1995** [mia-platform/custom-plugin-lib#222]
The proxy obtained by **getDirectServiceProxy** can not handle empty responses with status code = 200, because return the following syntax error: `SyntaxError: Unexpected end of JSON input`.

This error is thrown cause of automatic parse of response to JSON, in fact setting the **returnAs** option to BUFFER it's possible to go around the problem.

Workaround example:
```
const proxy = request.getDirectServiceProxy(BASE_URL)
const response = await proxy.post( `myURL`,  body,  querystring,  { returnAs: 'BUFFER'  })
```

**Comment by ilteoood** [comment]
@davidebianchi will this be fixed with the new http client?

**Comment by davidebianchi** [comment]
Yes, it is fixed with the new http client. In this commit I added the tests to verify it: [`b7ce7c9` (#221)](https://github.com/mia-platform/custom-plugin-lib/pull/221/commits/b7ce7c9afc88a7dcdf5d0b657055f8fe63ea4fed)

**Comment by davidebianchi** [comment]
This is now possible with the new http client and it will be released soon. I close the issue, since the other proxies are now deprecated.
