### ISSUE TITLE
Env variables from file are not read

### ISSUE THREAD

**Issue by fabio-percivaldi** [mia-platform/custom-plugin-lib#326]
We created a new service using the custom-plugin-lib version 5.1.5, from the changelog it's possible to see that there is a bug involving the environment variables that has been fixed with the 5.1.5 itself but even with the latest version we encounter a problem at the start up.
It seems that the environment variable file (default.env or local.env) is not read from the service.

the command i'm using is 
```
set -a && source default.env && npx lc39 build/index.js
```
or
```
set -a && source default.env && npm start
```
npm start is lc39 build/index.js

![image](https://user-images.githubusercontent.com/30175434/214056033-3007493c-6903-4718-ae3a-e50b8bd262ca.png)

i was not able to find the solution in the changelog of the custom plugin or lc39, do you know what could be the problem?

Changing the version to 4.3.2 solves the problem.

**Comment by ianFarreMia** [comment]
Hi, have you tried running the command like that `lc39 dist/index.js --env-path ./local.env`?
I have a service with this version of the custom-plugin-lib and it works as expected.

**Comment by fabio-percivaldi** [comment]
Hi @ianFarreMia ! same result, i tried with npx and installing lc39 globally
<img width="911" alt="image" src="https://user-images.githubusercontent.com/30175434/214074946-9c97e149-0114-4ff6-99e9-6ee86814320c.png">

**Comment by fabio-percivaldi** [comment]
those are the dependencies from package-lock.json
![image](https://user-images.githubusercontent.com/30175434/214075234-f43cc343-6d71-4837-b3f1-f64297c2f776.png)

**Comment by ianFarreMia** [comment]
That's weird, I have the same versions and it works just fine. Can you share the `default.env` file you are using? maybe replacing sensistive data if needed.

Another thing that could help is to do a nice `rm -rf node_modules` and `npm ci` afterwards.

**Comment by fabio-percivaldi** [comment]
maybe it's relevant, it's a typescript project, i have another project that is working with the 4.3.2 and also there if i update to the 5.1.5 it stops working so probably it's not the file anyway it's this:
LOG_LEVEL=trace
USERID_HEADER_KEY=userid
GROUPS_HEADER_KEY=usergroups
CLIENTTYPE_HEADER_KEY=clienttype
BACKOFFICE_HEADER_KEY=isbackoffice
MICROSERVICE_GATEWAY_SERVICE_NAME=microservice-gateway
CONFIGURATION_PATH=../tests/validConnectorsConfiguration

**Comment by ianFarreMia** [comment]
Honestly I'm out of ideas on what it could be :thinking: 

Maybe you can try this template https://github.com/mia-platform-marketplace/Typescript-LC39-Template (updating the custom-plugin-lib to the 5.1.5)

I would install the dependencies you are using in your project and then I'd try to do an `npm run start:local`. If it works I'd copy contents of the generated `package-lock.json` to your project and do a `rm -rf node_modules && npm ci`

**Comment by fabio-percivaldi** [comment]
i debugged a little bit inside the code and found that the problem is in the schema (https://github.com/mia-platform/custom-plugin-lib/blob/be2fb0e9149d8587841ac309e6c50e323b2d88ed/index.js#L111).

This function is using `schemaRemainingProperties` and `otherSchemaRemainingProperties` that in my case results in

```
allOf: [
    { type: 'object' },
    { type: 'object', additionalProperties: false }
  ],
```

this basically invalidate the entire object:
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/30175434/214257441-ac5fb142-c30d-4f09-8407-47ea22c9117b.png">

**Comment by fredmaggiowski** [comment]
nice catch @fabio-percivaldi do you think you can provide a fix in a PR?

**Comment by giuliowaitforitdavide** [comment]
Me and @fabio-percivaldi are working on that. The main think we want to understand, before applying a fix, is the output of this line of code. Is anything related to the additionalProperties of the schema?
I mean something like 
```json
{
  "type": "object",
  "properties": {
    "MICROSERVICE_GATEWAY_SERVICE_NAME": {
      "type": "string"
    },
	...
  },
  ...,
  "additionalProperties": {
    "type": "object"
  }
}
```

**Comment by ianFarreMia** [comment]
Hi, I will give you some context on that line: the `allOf` property was introduced to merge both the default schema of the plugin and the provided schema without them overwriting properties from one another. This was done to support `if-then-else, anyOf, oneOf...` properties.

**Comment by fabio-percivaldi** [comment]
> Hi, I will give you some context on that line: the `allOf` property was introduced to merge the default schema of the plugin and the provided schema without them overwriting properties from one another. This was done to support `if-then-else, anyOf, oneOf...` properties in the provided schema.

ok now the purpose is clearer, but in my opinion we can't merge `anyOf` or `oneOf` properties inside the `allOf` otherwise we are transforming something that act as an `or` into something that is more like an `and`.

If you agree my suggestion here is to define a specific behaviour for each keyword, does it make sense? or do you have another suggestion for the fix?

**Comment by ianFarreMia** [comment]
> ok now the purpose is clearer, but in my opinion we can't merge anyOf or oneOf properties inside the allOf otherwise we are transforming something that act as an or into something that is more like an and.

The point was to act as an `and` so we made sure it passed the validation both from the base schema and the provided schema.

>If you agree my suggestion here is to define a specific behaviour for each keyword, does it make sense? or do you have another suggestion for the fix?

Yes I agree, to avoid further similar bugs I would handle the `if-then-else, allOf, oneOf and anyOf` merge manually for now and skip other properties like it we did before.

**Comment by giuliowaitforitdavide** [comment]
Can we create a branch from this issue?

**Comment by fabio-percivaldi** [comment]
Hi everyone!

i wanted to know if we have an idea about when to merge this issue, we created a new service using this template https://github.com/mia-platform-marketplace/Node.js-Hello-World-Microservice-Example/blob/master/package.json that is using the version 5.0.0 of the custom plugin lib that has the bug, so for instance if you add a new environment variable to the ENV schema, the service does not start correctly.
