### ISSUE TITLE
Allow the proxies functions to receive query parameters as string into the path of the request

### ISSUE THREAD

**Issue by silversoul93** [mia-platform/custom-plugin-lib#44]
## The feauture or bug you are proposing
The proxies function, used by the proxies obtained with the `getServiceProxy` and `getDirectServiceProxy` functions, should allow the user to pass the `queryParameters` into the `path` of the request.

## A snippet of code for replicating the issue or showing the proposal usage if applicable
```javascript
const myProxy = service.getDirectServiceProxy('localhost:3000')
const response = await myProxy.get('/myPath?name=Mike&surname=Shinoda') //error
```

## The expected result for your bug
The code above should correctly work.

### Your environment

node: 12

custom-plugin-lib: v1.1.1

**Comment by fredmaggiowski** [comment]
The `get` function accepts query parameters as second argument, why do you need them to be encoded in the path?

[Here the line of code](https://github.com/mia-platform/custom-plugin-lib/blob/master/lib/serviceBuilder.js#L177)

**Comment by davidebianchi** [comment]
This is now possible with the new http client and it will be released soon. I close the issue, since the other proxies are now deprecated.
